# Generated by Django 5.0 on 2024-11-27 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
        ('vehiculos', '0005_vehiculo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo'),
        ),
    ]
