# Generated by Django 5.0 on 2024-12-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0002_suscripcion_pagosuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
