# Generated by Django 5.1.2 on 2024-11-15 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/vehiculos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.vehiculo')),
            ],
        ),
    ]
