# Generated by Django 5.1.2 on 2024-11-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
    ]
