# Generated by Django 5.1.2 on 2024-11-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
    ]
